include: package:flutter_lints/flutter.yaml

linter:
    rules:
        # Code Structure
        avoid_redundant_argument_values: true
        prefer_asserts_with_message: true
        prefer_const_constructors: true
        prefer_final_fields: true
        prefer_void_to_null: true

        # Style
        prefer_single_quotes: true
        avoid_double_and_int_checks: true
        prefer_int_literals: true
        prefer_adjacent_string_concatenation: true
        sort_pub_dependencies: true
        sort_constructors_first: true
        curly_braces_in_flow_control_structures: true

        # Errors
        throw_in_finally: false
        avoid_catches_without_on_clauses: true
        avoid_empty_else: true
        avoid_relative_lib_imports: true

        # Performance
        avoid_slow_async_io: true
        prefer_is_empty: true
        avoid_annotating_with_dynamic: true
        avoid_returning_this: true
        prefer_is_not_empty: true
        unnecessary_lambdas: true

        # Best Practices
        annotate_overrides: true
        use_rethrow_when_possible: true
        implementation_imports: true
        no_runtimeType_toString: true
        avoid_shadowing_type_parameters: true
        avoid_null_checks_in_equality_operators: true
        prefer_const_constructors_in_immutables: true
